language: node_js
node_js: 8.15.1
services:
  - docker
#env:
 # - SECRET=somesecretkey
cache:
  directories:
    - "node_modules"
before_script:
  - npm update -q
  - cd application
  - npm install
jobs:
  include:
    - stage: "Tests"
      name: "Unit Test"
      script: npm run test:unit
    - script: npm run test:integration
      name: "Integration Test"
    - stage: "Package"
      cache: 
        directories:
          - ./application/dist
      script: npm run build
    - stage: "Deploy to development"
      deploy:
        provider:
        api_key:
          secure:
        file: "./dist"
        skip_cleanup: true
        app: "nome do dominio"
        on:
          brancher:
            only:
              - developer
            tags: true

    - stage: "Deploy to production"
      deploy:
        provider: 'heroku'
        api_key: 
          secure: "<encrypted-token>"
        file: "./dist"
        skip_cleanup: true
        app: "nome do dominio"
        on:
          branches:
            only: 
              - master
          tags: true


#deploy:
 # provider: "host"
 # api_key: ...
 # app:
  #  master: my-app-staging
  #  release: 