language: node_js
node_js: 8.15.1
services:
  - docker
#env:
 # - SECRET=somesecretkey
cache:
  directories:
    - "node_modules"
before_script:
  - npm update -q
  - cd application
  - npm install
jobs:
  include:
    #- stage: "Tests"
     # name: "Unit Test"
      #script: npm run test:unit
    #- script: npm run test:integration
     # name: "Integration Test"
    #- stage: "Package"
     # script: npm run build
    - stage: "Deploy"
      deploy:
        provider: releases
        api_key: ${api_key}
        file: "./application/dist"
        skip_cleanup: true
        #app: "nome do dominio"
        on:
          brancher:
            only:
              - master
            

    #- stage: "Deploy to production"
     # deploy:
      #  provider: releases
       # api_key: 
        #  secure: "<encrypted-token>"
        #file: "./dist"
        #skip_cleanup: true
        #app: "nome do dominio"
        #on:
         # branches:
          #  only: 
           #   - master
          #tags: true


#deploy:
 # provider: "host"
 # api_key: ...
 # app:
  #  master: my-app-staging
  #  release: 
  # e5a6c3c8b83516ad8c1f57a3a4e0074d08e72219