sudo: false
language: node_js
node_js: 8.15.1
services:
  - docker
env:
  - SECRET=somesecretkey
cache:
  directories:
    - "node_modules"
before_script:
  - npm update -q
  - npm install
  # - npm install -g heroku
stages:
  - compile
  - tests
  - deploy

jobs:
  include:
    - stage: tests
      name: "Unit Test"
      script: npm run test:unit
    - script: npm run test:integration
      name: "Integration Test"
    - stage: deploy to develop
      script: true
      deploy: &heroku
        skip_cleanup: true
        provider: heroku
        app: party-development
        api_key: ${api_key}
        on: 
          repo: rodrigoRolim/party
          all_branches: true
     # on: develop
    - stage: test develop
      script: "curl https://party-development.herokuapp.com"
      
    - stage: deploy to release
      script: skip
      deploy: 
        <<: *heroku
        app: party-release
      on: /^release-.*$/
    - stage: test release
      script: "curl https://party-release.herokuapp.com"