sudo: false
language: node_js
node_js: 8.15.1
services:
  - docker

cache:
  directories:
    - "node_modules"
before_script:
  - npm update -q
  - npm install

stages:
  - compile
  - tests
  - name: deploy to staging
    if: branch = staging
  - name: deploy to production
    if: branch = master


jobs:
  include:
    - stage: tests
      name: "Unit Test"
      script: npm run test:unit
    - script: npm run test:integration
      name: "Integration Test"
    - stage: deploy to staging
      script: skip
      deploy:
        skip_cleanup: true
        provider: heroku
        app: app-party-staging
        api_key: ${api_key}
        on: 
          repo: rodrigoRolim/party
          branch: staging

    - stage: deploy to production
      deploy:
        provider: elasticbeanstalk
        access_key_id: 
          secure: ${key_aws_id}
        secret_access_key:
          secure: ${secret_key_aws}
        region: "us-west-2"  
        app: "app-party"
        env: "AppParty-env"
        bucket_name: "elasticbeanstalk-us-west-2-862757557765"
        on:
          branch: master