language: node_js
node_js: 8.15.1
services:
  - docker
#env:
 # - SECRET=somesecretkey
cache:
  directories:
    - "node_modules"
before_script:
  - npm update -q
  - cd application
  - npm install
jobs:
  include:
    - stage: "Tests"
      name: "Unit Test"
      script: npm run test:unit
    - script: npm run test:integration
      name: "Integration Test"
    - stage: "Build"
      script: npm run build
    - stage: "Deploy"
      deploy:
        provider: 'heroku'
        api_key: 
          secure: "<encrypted-token>"
        file: 'dist'
        skip_cleanup: true
        on:
          branches:
            only: 
            - master
          tags: true

